const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const { agentPanelSource } = require('./helpers/agent-panel-source')

const main = fs.readFileSync(path.join(__dirname, '..', 'electron', 'main.js'), 'utf8')
const preload = fs.readFileSync(path.join(__dirname, '..', 'electron', 'preload.js'), 'utf8')
const library = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'MediaLibrary.tsx'), 'utf8')
const sidebar = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'Sidebar.tsx'), 'utf8')
const workbench = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'Workbench.tsx'), 'utf8')
const panel = agentPanelSource()
const app = fs.readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
const types = fs.readFileSync(path.join(__dirname, '..', 'src', 'types', 'global.d.ts'), 'utf8')

test('home:open combines file and directory selection in one dialog', () => {
  assert.match(main, /ipcMain\.handle\('home:open'/)
  assert.match(main, /'openFile', 'openDirectory', 'multiSelections'/)
  assert.match(main, /authorizedFolders\.add\(folder\)/)
  assert.match(main, /splitAndApproveAny\(files\)/)
  assert.match(preload, /home: \{/)
  assert.match(preload, /open: \(\) => ipcRenderer\.invoke\('home:open'\)/)
  assert.match(types, /folders: string\[\]/)
})

test('capability drawer preserves open, analysis, cast, libraries and model center without emoji navigation', () => {
  for (const label of ['打开', '拉片', '投屏', '本地媒体', '在线媒体库', '模型接入中心', '全部能力']) {
    assert.ok(sidebar.includes(label), '能力抽屉缺：' + label)
  }
  for (const retired of ['📂', '🎬', '📺', '🧩']) {
    assert.ok(!sidebar.includes(retired), '活动轨道不应保留表情符号：' + retired)
  }
  assert.match(sidebar, /workspace-capability-flyout/)
  assert.match(sidebar, /ai-player-ask-open-mode/)
  assert.match(main, /ipcMain\.handle\('home:open-folder'/)
  assert.match(preload, /openFolder: \(\) => ipcRenderer\.invoke\('home:open-folder'\)/)
  assert.match(app, /ai-player-open-folder/)
  assert.match(app, /ai-player-attach-docs/)
  assert.ok(!library.includes('📂 打开'), '媒体库内不应再有重复打开按钮')
  assert.match(app, /<Workbench/)
  assert.match(app, /<MediaLibrary onPlay=\{playMedia\} rootDir=\{libraryRoot\}(?: actionRequest=\{libraryActionRequest\})? \/>/)
})

test('analysis still opens the unified chat flow, and the home uses one intent entrance', () => {
  assert.match(sidebar, /openAnalysisChat/)
  assert.match(sidebar, /就自动下载并开始拉片/)
  assert.doesNotMatch(sidebar, /detail: 'analysis-studio'/)
  assert.match(panel, /把任何事情交给我/)
  assert.match(panel, /今天想完成什么？/)
  assert.match(panel, /下载一个视频/)
  assert.match(panel, /agent-composer-wrap-home/)
  const emptyBlock = library.slice(library.indexOf('这里还没有媒体文件'), library.indexOf('这里还没有媒体文件') + 900)
  assert.ok(!emptyBlock.includes('📂 打开'), '空媒体库不应再有第二个打开入口')
})

test('recent work and adaptive focus mode replace the old resizable three-pane console', () => {
  assert.match(sidebar, /继续任务或重新播放/)
  assert.match(sidebar, /tasks\.slice\(0, 10\)\.map/)
  assert.match(sidebar, /agentplay-open-task-center/)
  assert.match(sidebar, /recentMedia\.map/)
  assert.match(sidebar, /setMedia\(item\.name, item\.src\)/)
  assert.ok(!library.includes('RecentStrip'), '媒体库内的 RecentStrip 应已移除')
  assert.match(workbench, /workspace-home-main/)
  assert.match(workbench, /workspace-focus-canvas/)
  assert.match(workbench, /workspace-focus-assistant/)
  assert.match(workbench, /showRail = !theater && \(!rightOpen \|\| pinned\)/)
  assert.match(workbench, /aiplayer_left_pinned/)
  assert.doesNotMatch(workbench, /cursor-col-resize/)
  assert.doesNotMatch(workbench, /aiplayer_left_w|aiplayer_right_w/)
  assert.match(panel, /open=\{showServiceEdit\}/)
  assert.match(panel, /运行方式与可选服务/)
  assert.match(app, /rightOpen = Boolean\(videoSrc\)/)
  assert.match(app, /clearMedia/)
})
