const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('main process owns planning, frozen execution, recovery and cancellation for exact trim jobs', () => {
  const main = read('electron/main.js')
  assert.match(main, /compileEditDecisionList/)
  assert.match(main, /new MediaEditService\(\{ frames: videoFrames \}\)/)
  assert.match(main, /persistentTaskRuntime\.register\('media\.edit-trim'/)
  const executor = main.slice(main.indexOf("persistentTaskRuntime.register('media.edit-trim'"), main.indexOf("persistentTaskRuntime.register('media.edit-remove'"))
  assert.equal((executor.match(/validateMediaSources\(task\.spec\.sources\)/g) || []).length, 2, '剪辑前后都必须复核源文件指纹')
  assert.match(main, /mediaEditService\.trim\(\{[\s\S]{0,240}decision: task\.spec\.decision[\s\S]{0,240}signal/)
  assert.match(main, /checkpoint\(\{ stage: 'artifact-written', result/)
  assert.match(main, /ipcMain\.handle\('media:edit-plan'/)
  assert.match(main, /ipcMain\.handle\('media:trim'/)
  assert.match(main, /请明确说“保留第4秒到第20秒”“删除第4秒到第8秒”或“把第8秒到第12秒放前面，再接第0秒到第4秒”/)
  assert.match(main, /const taskType = decision\.kind === 'media\.concat-sources'/)
  assert.match(main, /decision\.kind === 'media\.concat-segments'/)
  assert.match(main, /type: taskType/)
  assert.match(main, /plannedMediaOutput\(outputAnchor, decision\.output\.suffix, outputExtension, requestId\)/)
})

test('main process attaches and revalidates the canonical EDL before every persistent edit execution', () => {
  const main = read('electron/main.js')
  const edl = read('electron/edit-decision-list.js')
  assert.match(main, /const \{ assertEditDecisionList, attachEditDecisionList \} = require\('\.\/edit-decision-list'\)/)
  assert.match(main, /const decision = rawDecision \? attachEditDecisionList\(rawDecision\) : null/)
  assert.ok((main.match(/assertEditDecisionList\(decision\)/g) || []).length >= 10, '每种持久编辑执行器都必须复核 EDL')
  assert.match(edl, /EDL 与冻结决策不一致/)
})

test('main process persists an edit capsule before checkpointing and owns undo or redo navigation', () => {
  const main = read('electron/main.js')
  assert.match(main, /new MediaEditProjectStore\(\{ rootDir: path\.join\(app\.getPath\('userData'\), 'media-edit-projects'\) \}\)/)
  const executor = main.slice(main.indexOf("persistentTaskRuntime.register('media.edit-trim'"), main.indexOf("persistentTaskRuntime.register('media.edit-remove'"))
  assert.match(executor, /mediaEditProjects\.recordEdit\(\{[\s\S]{0,260}taskId: task\.id[\s\S]{0,260}sourcePath[\s\S]{0,260}outputPath/)
  assert.ok(executor.indexOf('mediaEditProjects.recordEdit') < executor.indexOf("checkpoint({ stage: 'artifact-written'"), '项目版本必须先持久化再收口任务检查点')
  assert.match(main, /ipcMain\.handle\('media:edit-history-plan'/)
  assert.match(main, /ipcMain\.handle\('media:edit-history'/)
  assert.match(main, /mediaEditProjects\.navigate\(\{ currentPath, direction: action\.action \}\)/)
})

test('preload exposes planning, trim execution, project navigation and the shared persistent cancel route', () => {
  const preload = read('electron/preload.js')
  const types = read('src/types/global.d.ts')
  assert.match(preload, /planEdit: \(input\) => ipcRenderer\.invoke\('media:edit-plan', input\)/)
  assert.match(preload, /planHistory: \(input\) => ipcRenderer\.invoke\('media:edit-history-plan', input\)/)
  assert.match(preload, /navigateHistory: \(input\) => ipcRenderer\.invoke\('media:edit-history', input\)/)
  assert.match(preload, /trim: \(input\) => ipcRenderer\.invoke\('media:trim', input\)/)
  assert.match(preload, /mediaTools:[\s\S]{0,600}cancel: \(requestId\) => ipcRenderer\.invoke\('media:task-cancel', requestId\)/)
  assert.match(types, /planEdit: \(input: \{ instruction: string; sourcePath: string; clarificationId\?: string \}/)
  assert.match(types, /planHistory: \(input: \{ instruction: string; currentPath: string \}/)
  assert.match(types, /navigateHistory: \(input: \{ instruction: string; currentPath: string \}/)
  assert.match(types, /trim: \(input: \{ instruction: string; sourcePath: string; requestId: string;/)
  assert.match(types, /interface EditDecisionListV1/)
  assert.match(types, /edl: EditDecisionListV1/)
})

test('renderer routes only a main-process-confirmed edit plan into a visible recoverable task', () => {
  const router = read('src/components/agent-panel/intentRouter.ts')
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const panel = read('src/components/AgentPanel.tsx')
  const recovery = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const dispatcher = read('src/components/agent-panel/taskCommandDispatcher.ts')
  const lifecycle = read('src/taskLifecycle.ts')
  assert.match(router, /if \(videoSrc[\s\S]{0,220}await runTrimTask\(text\)[\s\S]{0,80}return/)
  assert.ok(router.indexOf('await runTrimTask(text)') < router.indexOf('await runCompressTask(text)'))
  assert.match(tasks, /mediaTools\.planEdit\(\{ instruction: text, sourcePath, \.\.\.\(pendingClarification \? \{ clarificationId: pendingClarification\.id \}/)
  assert.match(tasks, /mediaTools\.trim\(\{ sourcePath, instruction: executionInstruction, requestId, workspaceTaskId:/)
  assert.match(tasks, /timelineReceipt/)
  assert.match(tasks, /result\.projectCapsule/)
  assert.match(tasks, /可直接说“撤销刚才的剪辑”/)
  assert.match(tasks, /ai-player-play-file/)
  assert.match(tasks, /case 'trim':/)
  assert.match(panel, /runTrimTask/)
  assert.match(recovery, /runtimeTask\.type === 'media\.edit-trim'/)
  assert.match(recovery, /isDownload \|\| isCreative \|\| isTimelineEdit/)
  assert.match(dispatcher, /case 'trim':[\s\S]{0,180}mediaTools\?\.cancel\(requestId\)/)
  assert.match(lifecycle, /'trim'/)
})

test('renderer routes a confirmed undo or redo action back to the project version and player', () => {
  const router = read('src/components/agent-panel/intentRouter.ts')
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const panel = read('src/components/AgentPanel.tsx')
  assert.match(router, /await runEditHistoryTask\(text\)/)
  assert.ok(router.indexOf('await runEditHistoryTask(text)') < router.indexOf('await runTrimTask(text)'))
  assert.match(tasks, /mediaTools\.planHistory\(\{ instruction: text, currentPath \}\)/)
  assert.match(tasks, /mediaTools\.navigateHistory\(\{ instruction: text, currentPath \}\)/)
  assert.match(tasks, /result\.versionCount/)
  assert.match(tasks, /ai-player-play-file/)
  assert.match(panel, /runEditHistoryTask/)
})

test('remove-segment decisions enter their own recoverable task and the shared edit project', () => {
  const main = read('electron/main.js')
  const executorStart = main.indexOf("persistentTaskRuntime.register('media.edit-remove'")
  const executorEnd = main.indexOf("persistentTaskRuntime.register('media.dedup'")
  const executors = main.slice(executorStart, executorEnd)
  assert.match(executors, /persistentTaskRuntime\.register\('media\.edit-remove'/)
  assert.match(executors, /decision\.kind !== 'media\.remove-segment'/)
  assert.match(executors, /mediaEditService\.removeSegment/)
  assert.match(executors, /mediaEditProjects\.recordEdit\(\{[\s\S]{0,260}taskId: task\.id/)
  assert.match(main, /const taskType = decision\.kind === 'media\.concat-sources'/)
  assert.match(main, /decision\.kind === 'media\.concat-segments'/)
  assert.match(main, /type: taskType/)
  assert.match(main, /type === 'media\.edit-trim' \|\| type === 'media\.edit-remove'/)
})

test('renderer presents remove-segment as a recoverable edit with every timeline mapping', () => {
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const runtime = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const types = read('src/types/global.d.ts')
  assert.match(tasks, /\['media\.trim', 'media\.remove-segment', 'media\.concat-segments', 'media\.add-music', 'media\.concat-sources', 'media\.burn-subtitles', 'media\.shift-subtitles', 'media\.mux-subtitles', 'media\.translate-subtitles', 'media\.edit-subtitle-cues'\]\.includes\(decision\.kind\)/)
  assert.match(tasks, /decision\.kind === 'media\.remove-segment' \? 'remove'/)
  assert.match(tasks, /timelineReceipt \|\| \[\]\)\.map/)
  assert.match(tasks, /start_remove_video_segment/)
  assert.match(runtime, /runtimeTask\.type === 'media\.edit-trim' \|\| runtimeTask\.type === 'media\.edit-remove' \|\| runtimeTask\.type === 'media\.edit-concat' || runtimeTask\.type === 'media\.edit-music'/)
  assert.match(types, /kind: 'media\.trim' \| 'media\.remove-segment' \| 'media\.concat-segments' \| 'media\.add-music' \| 'media\.concat-sources' \| 'media\.burn-subtitles' \| 'media\.shift-subtitles' \| 'media\.mux-subtitles' \| 'media\.translate-subtitles' \| 'media\.edit-subtitle-cues'/)
})

test('concat decisions run as their own persistent task and repair from the same frozen timeline', () => {
  const main = read('electron/main.js')
  const start = main.indexOf("persistentTaskRuntime.register('media.edit-concat'")
  const end = main.indexOf("persistentTaskRuntime.register('media.dedup'")
  const executor = main.slice(start, end)
  assert.ok(start > 0, 'multi-segment concat must have a main-process persistent executor')
  assert.match(executor, /decision\.kind !== 'media\.concat-segments'/)
  assert.match(executor, /mediaEditService\.concatSegments/)
  assert.match(executor, /mediaEditProjects\.recordEdit\(\{[\s\S]{0,260}taskId: task\.id/)
  assert.match(main, /decision\.kind === 'media\.concat-segments'[\s\S]{0,100}'media\.edit-concat'/)
  assert.match(main, /type === 'media\.edit-concat'/)
})

test('ambiguous edits return one clarification before any persistent media task is enqueued', () => {
  const main = read('electron/main.js')
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const router = read('src/components/agent-panel/intentRouter.ts')
  assert.match(main, /new MediaEditConversation\(\)/)
  assert.match(main, /mediaEditConversation\.plan\(\{ instruction: input\.instruction, sourcePath, clarificationId: input\.clarificationId \}\)/)
  const plannerStart = main.indexOf("ipcMain.handle('media:edit-plan'")
  const plannerEnd = main.indexOf("ipcMain.handle('media:edit-history-plan'", plannerStart)
  const planner = main.slice(plannerStart, plannerEnd)
  assert.doesNotMatch(planner, /persistentTaskRuntime\.enqueue/)
  assert.match(tasks, /pendingEditClarificationRef/)
  assert.match(tasks, /clarificationId: pendingClarification\.id/)
  assert.match(tasks, /plan\?\.clarification/)
  assert.match(tasks, /addMessage\('agent', plan\.clarification\.question\)/)
  assert.match(router, /EDIT_WITHOUT_SOURCE_INTENT/)
  assert.match(router, /请先打开或拖入要编辑的视频/)
})

test('renderer and preload contracts present concat and reorder as one recoverable editing action', () => {
  const tasks = read('src/components/agent-panel/useMediaCreativeTasks.ts')
  const runtime = read('src/components/agent-panel/usePersistentTaskRuntime.ts')
  const types = read('src/types/global.d.ts')
  assert.match(tasks, /'media\.concat-segments'/)
  assert.match(tasks, /start_concat_video_segments/)
  assert.match(tasks, /按顺序拼接/)
  assert.match(runtime, /runtimeTask\.type === 'media\.edit-concat' || runtimeTask\.type === 'media\.edit-music'/)
  assert.match(runtime, /拼接/)
  assert.match(types, /kind: 'media\.trim' \| 'media\.remove-segment' \| 'media\.concat-segments' \| 'media\.add-music' \| 'media\.concat-sources' \| 'media\.burn-subtitles' \| 'media\.shift-subtitles' \| 'media\.mux-subtitles' \| 'media\.translate-subtitles' \| 'media\.edit-subtitle-cues'/)
  assert.match(types, /segments: Array<\{ sourceStartSeconds: number; sourceEndSeconds: number;/)
})
