const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const { agentPanelSource } = require('./helpers/agent-panel-source')

const read = (file) => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')
const store = read('src/stores/agentStore.ts')
const panel = agentPanelSource()
const center = read('src/components/TaskCenter.tsx')
const sidebar = read('src/components/Sidebar.tsx')
const css = read('src/index.css')

test('workspace tasks persist locally and fail-close unfinished work on hydration', () => {
  assert.match(store, /persist\(/)
  assert.match(store, /name: 'agentplay-workspace-tasks'/)
  assert.match(store, /partialize: \(state\) => \(\{ tasks: state\.tasks, activeTaskId: state\.activeTaskId, agentMode: state\.agentMode \}\)/)
  assert.match(store, /restoreWorkspaceTasks\(stored\.tasks\)/)
  assert.match(store, /onRehydrateStorage/)
  assert.match(store, /useAgentStore\.setState\(\{ tasks, activeTaskId, task/)
  assert.match(store, /retryTask: \(id\)/)
  assert.match(store, /clearFinishedTasks/)
})

test('download, link analysis, documents and media jobs enter the same task ledger', () => {
  assert.match(panel, /startTask\(\{ kind: 'download'/)
  assert.match(panel, /startTask\(\{ kind: 'link-analysis'/)
  assert.match(panel, /startTask\(\{ kind: 'doc'/)
  assert.match(panel, /startTask\(\{ kind: 'analysis'/)
  assert.match(panel, /startTask\(\{\s*kind: 'media'/)
  assert.match(panel, /phase: 'waiting', status: '等待允许云端处理'/)
  assert.match(panel, /phase: 'completed'(?: as const)?, running: false/)
  assert.match(panel, /completeExecutionTask\(\{ summary: `已扫描 \$\{result\.filesScanned\} 个媒体文件，没有发现内容重复` \}\)/)
  assert.match(panel, /const failExecutionTask = \(error: string, patch: Partial<AgentTask> = \{\}\)/)
  assert.match(panel, /downloadDirectRef\.current = direct/)
  assert.match(panel, /cancellableTaskId=\{cancellableTaskId\}/)
  assert.match(panel, /后台没有确认取消，任务状态保持不变/)
  assert.match(panel, /busy=\{docBusy\}[\s\S]{0,160}cancellable=\{Boolean\(cancellableTaskId\)\}/)
  assert.match(panel, /disabled=\{busy && !cancellable\}/)
  assert.match(center, /task\.id === cancellableTaskId/)
})

test('running updates stay bound to execution task id while users inspect history', () => {
  assert.match(store, /updateTask: \(id: string, patch: Partial<AgentTask>\) => void/)
  assert.match(store, /state\.activeTaskId === id \? \{ task: next \} : \{\}/)
  assert.match(panel, /const executionTaskIdRef = useRef\(''\)/)
  assert.match(panel, /updateTask\(executionTaskIdRef\.current, patch\)/)
  assert.match(panel, /executionTaskIdRef\.current = startTask/)
  const workbench = read('src/components/Workbench.tsx')
  assert.match(workbench, /const journeyTask = tasks\.find/)
})
test('task center exposes progress, results, safe retry and cancellation without crowding home', () => {
  assert.match(center, /任务与结果/)
  assert.match(center, /task\.outputs\.slice\(0, 4\)/)
  assert.match(center, /openPath\(output\)/)
  assert.match(center, /showInFolder\(output\)/)
  assert.match(center, /再次执行/)
  assert.match(center, /继续修改/)
  assert.match(center, /取消任务/)
  assert.match(center, /taskTimingForTask/)
  assert.doesNotMatch(center, /task\.progress \?\? 30/)
  assert.match(center, /任务执行步骤/)
  assert.match(center, /份证据已验证/)
  assert.match(center, /成果证据/)
  assert.match(center, /task\.evidence\.slice\(0, 4\)/)
  assert.match(center, /task\.budget\.toolCalls/)
  assert.match(panel, /system\.verifyPaths\(outputs\)/)
  assert.match(panel, /来源指纹已冻结/)
  assert.match(panel, /成果包一致性已验证/)
  assert.match(panel, /useContinueTask/)
  assert.match(panel, /showTaskCenter &&/)
  assert.match(panel, /这个任务需要重新授权原文件/)
  assert.match(css, /TASK CENTER V1/)
})

test('activity rail recent view resumes persisted tasks and keeps recent media as fallback', () => {
  assert.match(sidebar, /const tasks = useAgentStore/)
  assert.match(sidebar, /selectTask\(task\.id\)/)
  assert.match(sidebar, /agentplay-open-task-center/)
  assert.match(sidebar, /继续任务或打开结果/)
  assert.match(sidebar, /recentMedia\.slice/)
})
